apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: countries-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mamunreza/countries-api-k8s.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: countries-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true